### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Tux-Panik** [Basicb4/Spam-Button#1]
Dear,
Sorry, but the installation steps are not enough precise.

What should be done after tuning the SPAM mailbox?
How to install the button?
Is, this ribbon, installable using a GPo?

Thanks for your support,
Regards,
Julien

**Comment by bobafettCH** [comment]
hi Julien,
do you got some input about the installation of the 

> Dear,
> Sorry, but the installation steps are not enough precise.
> What should be done after tuning the SPAM mailbox?
> How to install the button?
> Is, this ribbon, installable using a GPo?
> Thanks for your support,
> Regards,
> Julien

Hi Julien,

do you got some information about the installation of the SPAM Button? I have the same problem.
Regards
reto

**Comment by Tux-Panik** [comment]
Unfortunately I don't.
